=== smartcommunitylab/smartcampus.socialservice/src/test/resources/resourceTemplateSchema.xsd
<?xml version="1.0"?>
<!-- Copyright 2012-2013 Trento RISE Licensed under the Apache License, Version 
	2.0 (the "License"); you may not use this file except in compliance with 
	the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 
	Unless required by applicable law or agreed to in writing, software distributed 
	under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
	OR CONDITIONS OF ANY KIND, either express or implied. See the License for 
	the specific language governing permissions and limitations under the License. -->
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

    <xsd:element name="service" type="service"/>

	<xsd:complexType name="service">
		<xsd:sequence>
			<xsd:element minOccurs="0" maxOccurs="unbounded" name="resource"
				type="resourceDeclaration" />
			<xsd:element minOccurs="0" maxOccurs="unbounded" name="resourceMapping"
				type="resourceMapping" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="resourceDeclaration">
		<xsd:attribute name="id" type="xsd:ID" use="required" />
	</xsd:complexType>

	<xsd:complexType name="resourceMapping">
		<xsd:attribute name="method" type="xsd:string" />
		<xsd:attribute name="uri" type="xsd:string" use="required"/>
		<xsd:attribute name="pathPattern" type="xsd:string" use="required"/>
	</xsd:complexType>

</xsd:schema>

=== smartcommunitylab/smartcampus.socialservice/src/main/resources/resourceList.xml
<?xml version="1.0" standalone="yes"?>
<!-- Copyright 2012-2013 Trento RISE Licensed under the Apache License, Version 
	2.0 (the "License"); you may not use this file except in compliance with 
	the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 
	Unless required by applicable law or agreed to in writing, software distributed 
	under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
	OR CONDITIONS OF ANY KIND, either express or implied. See the License for 
	the specific language governing permissions and limitations under the License. -->
<service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="classpath:../../../../resource.api/src/main/resources/jaxb/binding/resourceTemplateSchema.xsd">

	<resource id="communityId" />
	<resource id="commentId" />
	<resource id="localId" />
	<resource id="appId" />
	<resource id="userId" />
	<resource id="uri" />

	<!-- user groups -->
	<resourceMapping uri="socialservice.user.group.read"
		pathPattern="/user/group/{groupId}" method="GET" />
	<resourceMapping uri="socialservice.user.group.read"
		pathPattern="/user/group" method="GET" />
	<resourceMapping uri="socialservice.user.group.write"
		pathPattern="/user/group/{groupId}" method="PUT,DELETE" />
	<resourceMapping uri="socialservice.user.group.write"
		pathPattern="/user/group" method="POST" />
	<resourceMapping uri="socialservice.user.group.write"
		pathPattern="/user/group" method="PUT,DELETE" />
	<resourceMapping uri="socialservice.user.group.write"
		pathPattern="/user/group/{groupId}/members" method="PUT,DELETE" />

	<!-- user communities -->
	<resourceMapping uri="socialservice.user.community.read"
		pathPattern="/user/community" method="GET" />
	<resourceMapping uri="socialservice.user.community.write"
		pathPattern="/user/community/{communityId}/member" method="PUT,DELETE" />

	<!-- community -->
	<resourceMapping uri="socialservice.community.all"
		pathPattern="/community" method="GET" />
	<resourceMapping uri="socialservice.community.all"
		pathPattern="/community/{communityId}" method="GET" />
	<resourceMapping uri="socialservice.community.all"
		pathPattern="/community/social/{socialId}" method="GET" />
	<resourceMapping uri="socialservice.community.{appId}.write"
		pathPattern="/app/{appId}/community" method="POST" />
	<resourceMapping uri="socialservice.community.{appId}.write"
		pathPattern="/app/{appId}/community/{communityId}" method="DELETE" />
	<resourceMapping uri="socialservice.community.{appId}.write"
		pathPattern="/app/{appId}/community/{communityId}/members" method="PUT,DELETE" />


	<!-- sharing -->
	
	<!-- creation entity -->
	<resourceMapping uri="socialservice.app.{appId}.entities.write"
		pathPattern="/app/{appId}/{userId}/entity/create" method="POST" />
	
	<!-- update entity -->
	<resourceMapping uri="socialservice.app.{appId}.entities.manage"
		pathPattern="/app/{appId}/{userId}/entity/update" method="PUT" />
	
	<resourceMapping uri="socialservice.user.{appId}.entities.manage"
		pathPattern="/user/{appId}/entity/update" method="PUT" />
	
	<!-- delete entity -->
	<resourceMapping uri="socialservice.app.{appId}.entities.manage"
		pathPattern="/app/{appId}/entity/{localId}" method="DELETE" />
	
	<resourceMapping uri="socialservice.user.{appId}.entities.manage"
		pathPattern="/user/{appId}/entity/{localId}" method="DELETE" />
	
	<resourceMapping uri="socialservice.community.{appId}.entities.write"
		pathPattern="/app/{appId}/community/{communityId}/entity" method="POST" />
	
	<resourceMapping uri="socialservice.user.entities.read"
		pathPattern="/user/entity" method="GET" />
	
	<resourceMapping uri="socialservice.user.{appId}.entities.read"
		pathPattern="/user/{appId}/entity" method="GET" />
	
	<resourceMapping uri="socialservice.user.entities.read"
		pathPattern="/user/{appId}/entity/{localId}" method="GET" />
	
	<resourceMapping uri="socialservice.community.{appId}.entities.read"
		pathPattern="/app/{appId}/community/{communityId}/entity" method="GET" />
	
	<resourceMapping uri="socialservice.community.{appId}.entities.read"
		pathPattern="/app/{appId}/community/{communityId}/entity/{localId}"
		method="GET" />
	
	<resourceMapping uri="socialservice.user.{appId}.shared.read"
		pathPattern="/user/{appId}/shared" method="GET" />
	
	<resourceMapping uri="socialservice.user.shared.read"
		pathPattern="/user/shared" method="GET" />
	
	<resourceMapping uri="socialservice.user.shared.read"
		pathPattern="/user/{appId}/shared/{localId}" method="GET" />
	
	<resourceMapping uri="socialservice.community.{appId}.shared.read"
		pathPattern="/app/{appId}/community/{communityId}/shared" method="GET" />
	
	<resourceMapping uri="socialservice.community.{appId}.shared.read"
		pathPattern="/app/{appId}/community/{communityId}/shared/{localId}"
		method="GET" />
	
	
	<resourceMapping uri="socialservice.app.entity.info"
		pathPattern="/app/entity/{uri}/info"
		method="GET" />
	

	<!-- resource types -->
	<resourceMapping uri="socialservice.type.all"
		pathPattern="/type" method="GET" />
	<resourceMapping uri="socialservice.type.all"
		pathPattern="/type/{tid}" method="GET" />
	<resourceMapping uri="socialservice.type.all"
		pathPattern="/type" method="POST" />


	<!-- user entities comments -->
	<resourceMapping uri="socialservice.user.comment"
		pathPattern="/user/comment" method="GET" />
	<resourceMapping uri="socialservice.user.comment"
		pathPattern="/user/comment/{commentId}" method="GET,PUT,DELETE" />
	<resourceMapping uri="socialservice.user.comment"
		pathPattern="/user/{appId}/comment/{localId}" method="POST,GET,DELETE" />

	<!-- rating -->
	<resourceMapping uri="socialservice.user.rating"
		pathPattern="/user/{appId}/rating/{localId}" method="GET,POST,DELETE" />
</service>
